from sqlalchemy.orm import Session
from sqlalchemy import func, or_
from app.core.security import hashed_pasword
from app.models.userModel import UserModel
from app.schemas.userSchema import UserCreate,UserUpdate


class UserRepository:
    def __init__(self,db: Session):
        self.db=db

    def create_user(
        self,
        user: UserCreate,
        password_hash: str | None = None,
        is_active: bool = False,
    ) -> UserModel:
    # create_user = method/function name
    # self = the current UserRepository object
    # user = the data coming into this method
    # UserCreate = Pydantic schema/type of the incoming data
    # -> UserModel = this method will return a SQLAlchemy UserModel object

     user_values = user.model_dump(exclude={"password"})
     db_user = UserModel(
        **user_values,
        hashed_password=password_hash or hashed_pasword(user.password),
        is_active=is_active,
    )
    # user.model_dump()
    # → Converts the UserCreate Pydantic object into a Python dictionary
    #
    # Example:
    # UserCreate(name="Gaurav", email="test@gmail.com")
    #
    # becomes:
    # {
    #     "name": "Gaurav",
    #     "email": "test@gmail.com"
    # }
    #
    # ** expands that dictionary into keyword arguments:
    #
    # UserModel(
    #     name="Gaurav",
    #     email="test@gmail.com"
    # )
    #
    # db_user is now a SQLAlchemy UserModel object.


     self.db.add(db_user)
    # self
    # → The current UserRepository object
    #
    # self.db
    # → The database Session that you passed when creating
    #   UserRepository(db)
    #
    # .add()
    # → Tells SQLAlchemy:
    #   "I want to save this object to the database."
    #
    # db_user
    # → The UserModel object we created above.


     self.db.commit()
     # self.db
    # → Our SQLAlchemy database session
    #
    # .commit()
    # → Permanently commits the transaction.
    #
    # In simple words:
    # "Actually save the changes to PostgreSQL."


     self.db.refresh(db_user)
    # refresh()
    # → Gets the latest database values back into db_user.
    #
    # This is useful for values generated by the database,
    # such as:
    # - id
    # - created_at
    # - updated_at
    #
    # After refresh, db_user contains the latest database state.


     return db_user
    # return
    # → Sends the created user back to whoever called this method.
    #
    # db_user
    # → The SQLAlchemy UserModel object that was saved.

    def get_user_by_email(self, email: str) -> UserModel | None:
        # Case-insensitive: older accounts were stored with the email exactly as typed.
        return self.db.query(UserModel).filter(func.lower(UserModel.email) == email.strip().lower()).first()
    ###to get user by email, we query the database for a UserModel object where the email matches the provided email. If found, it returns the UserModel object; otherwise, it returns None.


    def get_active_user_by_number(self, number: str) -> UserModel | None:
        return (
            self.db.query(UserModel)
            .filter(UserModel.number == number.strip(), UserModel.is_active.is_(True))
            .first()
        )

    def get_user_by_id(self, user_id: str) -> UserModel | None:
        ###to get user by ID, we query the database for a UserModel object where the ID matches the provided ID. If found, it returns the UserModel object; otherwise, it returns None.
        return self.db.query(UserModel).filter(UserModel.id == user_id).first()
    
    def update_user(self, user_id: str, user_update: UserUpdate) -> UserModel | None:
        user = self.get_user_by_id(user_id)
        if not user:
            return None
        for field, value in user_update.model_dump(exclude_unset=True).items():
            setattr(user, field, value)
        self.db.commit()
        self.db.refresh(user)
        return user
    
    def delete_user(self, user_id: str) -> bool:
        user = self.get_user_by_id(user_id)
        if not user:
            return False
        self.db.delete(user)
        self.db.commit()
        return True
    
    def find_by_email_or_number(self, email: str, number: str) -> UserModel | None:
        return self.db.query(UserModel).filter(
            or_(func.lower(UserModel.email) == email.strip().lower(), UserModel.number == number)
        ).first()

    def check_user_exists(self, email: str,number: str) -> bool:
        return self.find_by_email_or_number(email, number) is not None

    def get_all_user(self,page:int=1 , page_size:int =10):
        skip = (page-1) * page_size
        return (
            self.db.query(UserModel).offset(skip).limit(page_size).all()
        )

    def list_patients(self) -> list[UserModel]:
        """Every non-doctor account, for the admin dashboard."""
        return self.db.query(UserModel).filter(UserModel.id_doctor == False).all()  # noqa: E712
        
