"""add is_admin or status

Revision ID: 028f6c994f4b
Revises: 0e58fe7bbc57
Create Date: 2026-09-20 07:51:21.317822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '028f6c994f4b'
down_revision: Union[str, Sequence[str], None] = '0e58fe7bbc57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('medplum_practitoner_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_medplum_practitoner_id'), 'users', ['medplum_practitoner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_medplum_practitoner_id'), table_name='users')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'medplum_practitoner_id')
    # ### end Alembic commands ###
